name: hallo_doctor_client
version: 1.0.18+12
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: 4.1.0
  cloud_firestore: ^4.1.0
  cloud_functions: 4.0.3
  firebase_storage: 11.0.3
  firebase_database: 10.0.5
  firebase_messaging: 14.1.0
  google_sign_in: ^5.3.3
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  string_validator: ^0.3.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.0
  date_picker_timeline: ^1.2.3
  flutter_stripe: ^5.1.0
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  http: ^0.13.4
  rounded_loading_button: ^2.1.0
  flutter_form_builder: 7.0.0
  form_builder_validators: ^8.1.1
  package_info_plus: ^1.4.2
  open_file: ^3.2.1
  file_picker: ^4.6.1
  uuid: ^3.0.6
  mime: ^1.0.2
  flutter_chat_ui:
    git: https://github.com/amsyary/flutter_chat_ui.git
  flutter_firebase_chat_core:
    git: https://github.com/amsyary/flutter_firebase_chat_core.git
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  jiffy: ^5.0.0
  agora_rtc_engine: ^5.3.1
  permission_handler: ^9.2.0
  flutter_callkit_incoming: ^1.0.2+1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  image_cropper: ^2.0.3
  sign_in_with_apple: ^4.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  build_runner: ^2.1.11
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/ic_launcher.png"
